# Homework 3 - Word Embedding & Rating Prediction

## 0. Introduction

### Goal and outline

In this notebook, our goal is to build a simple classification model and evaluate its performance when using the embedding matrices produced by three different embedding techniques: LSI, Word2Vec and FastText. 

In the three following sections we build the embedding matrices using each technique. Then, in section 4, we try to fit a cosine similarity classifier and a random forest classifier and evaluate its performances in predicting the ratings of the reviews as a target variable, with respect to the embeding matrices.

### Importing useful libraries

In [46]:
# Data manipulation
import numpy as np 
import pandas as pd 
import os.path

# Text manipulation
from string import punctuation
from wordcloud import WordCloud

# NLP Modules
import nltk
from nltk import word_tokenize
from nltk import WordNetLemmatizer
from nltk.stem import PorterStemmer
from nltk.corpus import stopwords
import re
import gensim
from gensim import corpora, similarities
from gensim.test.utils import common_dictionary, common_corpus
from gensim.test.utils import get_tmpfile
from gensim.models import LsiModel
import nltk
from nltk.tokenize import RegexpTokenizer
from gensim.models.coherencemodel import CoherenceModel

# Vizualisation
import seaborn as sns
import matplotlib as plt


# Extra imports

# Uncomment the following lines if you haven't installed gensim and nltk
#!pip3 install gensim
#!pip3 install nltk

# Downloading useful nltk packages if not already done
#nltk.download('stopwords')
#nltk.download('punkt')
#nltk.download('wordnet')

### Loading and preprocessing the data

In [47]:
# Here we use functions we defined in previous homework, running this cell takes few minutes

def load_data(DATA_PATH = "data/", file_name = "raw_scrapped_data.csv.gzip"):
    """
    Input  : path of where data is stored
    Purpose: loading csv file of reviews
    Output : data frame of reviews with associated ratings
    """    
    # Path of the file
    file_path = DATA_PATH + file_name

    # Reading data
    scrapped_data = pd.read_csv(file_path, compression='gzip')
    data = scrapped_data[['content', 'rating']]
    return data 

def basic_cleaning(series):
    # Remove punctuation
    new_series = series.str.replace('[^\w\s]','')
    # Strip trailing whitespace
    new_series = new_series.str.strip(" ")
    # Decapitalize letters
    new_series = new_series.apply(lambda x: str(x).lower())
    return new_series

def tokenize_filter(sentence):
    # Define stopwords
    stop_words = set(stopwords.words('english')) 
    ## Add personalised stop words
    stop_words |= set(["london", "food", "drink", "restaurant"])
    # Filter the sentence
    word_tokens = word_tokenize(sentence) 
    filtered_sentence = [w for w in word_tokens if not w in stop_words] 
    return (word_tokens, filtered_sentence)

def stem_review(tokens):
    porter = PorterStemmer()
    return tokens.apply(lambda x: [porter.stem(x[i]) for i in range(len(x))])

def preprocess_data(data):
    df = data
    df["clean_content"] = basic_cleaning(df["content"])
    df["tokenized_content"] = df["clean_content"].apply(lambda x: tokenize_filter(x)[1])
    df["stemmed_reviews"] = stem_review(df["tokenized_content"])
    return df[['stemmed_reviews', 'rating']]

df = preprocess_data(load_data())
df.head()

stemmed_reviews  rating
0  [decid, visit, windsor, castl, way, back, sw, ...       5
1  [good, although, rather, small, portion, howev...       2
2  [look, somewher, budget, go, eat, overnight, w...       5
3  [good, menu, select, unfortun, stifado, avail,...       4
4  [pop, last, night, glass, wine, attend, theatr...       3

## 1. Latent semantic indexing (LSI)

Here, we use the functions already defined in the handout and adapt them to our particular case

In [48]:
# We will use 100 reviews for now
reduced_df = df[:1000]

In [49]:
# 1. Using "corpora" from gensim to extract vocabulary from a corpus
def get_dictionary(doc_clean):
    """
    Input  : clean document
    Purpose: get the whole associated vocabulary
    Output : term dictionary
    """
    # Creating the term dictionary of our corpus, where every unique term is assigned an index. dictionary = corpora.Dictionary(doc_clean)
    return corpora.Dictionary(doc_clean)

In [50]:
# 2. Buildind TF matrix useful for LSI
def get_TF_matrix(doc_clean, useTransfertDict=True):
    """
    Input  : clean document
    Purpose: get the term frequency matrix from a corpus
    Output : Document Term Frequency Matrix
    """
    # Creating the term dictionary of our corpus, where every unique term is assigned an index. 
    dictionary = corpora.Dictionary(doc_clean)
        
    # Converting list of documents (corpus) into Document Term Matrix using dictionary prepared above.
    return [dictionary.doc2bow(doc) for doc in doc_clean]

In [51]:
# 3. Create an LSI model using Gensim
def create_gensim_lsi_model(clean_documents_list, k=None):
    """
    Input  : clean document, dictionary
    Purpose: create LSI model (Latent Semantic Indexing) 
             from corpus and dictionary
    Output : return LSI model
    """
    
    #LSI model consists of Singular Value Decomposition (SVD) of
    #Term Document Matrix M: M = T x S x D'
    #and dimensionality reductions of T, S and D ("Derivation")
    
    dictionary = get_dictionary(clean_documents_list)
    
    corpus = get_TF_matrix(clean_documents_list)
    if k is not None:
        lsi_model = LsiModel(
                corpus=corpus,
                id2word=dictionary,
                num_topics=int(k)
                )
    else:
            lsi_model = LsiModel(
            corpus=corpus,
            id2word=dictionary 
            )
    print(); print(); print("="*20, "Training LSI model report", "="*20); print()
    
    print("Initial TF matrix (NwordsXNdocuments): ")
    TF = []
    for x in corpus:
        wrds = [0 for i in range(len(dictionary))]
        for i, j in x: wrds[i] = j
        TF.append(wrds)
    print(pd.np.transpose(TF))
    print()
    print("Derivation of Term Matrix T of Training Document Word Stems: ")
    print(lsi_model.get_topics())
    print()
    #Derivation of Term Document Matrix of Training Document Word Stems = M' x [Derivation of T]
    print("LSI Vectors of Training Document Word Stems: ")
    print([lsi_model[document_word_stems] for document_word_stems in corpus])
    print("="*70); print(); print()
    return lsi_model

def get_lsi_vector(lsi_model, clean_text):
    return lsi_model[dictionary.doc2bow(clean_text)]

# create lsi model
lsi_model = create_gensim_lsi_model(reduced_df.stemmed_reviews)
# build encoded corpus (TF matrix)
corpus_TFmatrix = get_TF_matrix(reduced_df.stemmed_reviews)



==================== Training LSI model report ====================

Initial TF matrix (NwordsXNdocuments): 
[[1 0 0 ... 0 0 0]
 [1 0 0 ... 0 0 0]
 [2 0 0 ... 1 0 0]
 ...
 [0 0 0 ... 0 2 0]
 [0 0 0 ... 0 1 0]
 [0 0 0 ... 0 1 0]]

Derivation of Term Matrix T of Training Document Word Stems: 
[[ 2.35550898e-03  3.51214906e-04  4.12257024e-03 ...  2.30976527e-03
   1.15488263e-03  1.15488263e-03]
 [ 5.21497239e-03 -7.20731810e-05  6.71661400e-03 ... -5.63977793e-03
  -2.81988896e-03 -2.81988896e-03]
 [ 5.49123910e-03  5.71855628e-04  5.52210733e-03 ... -2.69197419e-03
  -1.34598709e-03 -1.34598709e-03]
 ...
 [ 7.47644070e-03  5.50465870e-03  2.19724503e-02 ... -1.72647380e-03
  -8.63236901e-04 -8.63236901e-04]
 [-6.49218673e-03 -6.34558874e-03 -3.41969377e-03 ...  9.99042438e-04
   4.99521219e-04  4.99521219e-04]
 [ 4.79715088e-03  2.03058037e-03  6.25104745e-03 ...  1.19538433e-03
   5.97692163e-04  5.97692163e-04]]

LSI Vectors of Training Document Word Stems: 


IOPub data rate exceeded.
The notebook server will temporarily stop sending output
to the client in order to avoid crashing it.
To change this limit, set the config variable
`--NotebookApp.iopub_data_rate_limit`.

Current values:
NotebookApp.iopub_data_rate_limit=1000000.0 (bytes/sec)
NotebookApp.rate_limit_window=3.0 (secs)



## 2. Word2Vec

In [52]:
# 1. Instantiating the model from gensim models
def create_word2vec_model():
    """
    Input  : none
    Purpose: create word2vec model from corpus
    Output : term dictionary
    """
    path = get_tmpfile("word2vec.model")
    model = gensim.models.Word2Vec(size=300, 
                                   window=3, 
                                   min_count=5, 
                                   workers=4, 
                                   seed=1, 
                                   iter=50)
    return model

In [53]:
# 2. Building model vocabulary
def init_vocab(model, clean_documents_list):
    """
    Input  : model and clean documents list
    Purpose: instantiate model vocabulary from clean documents list
    Output : model with vocabulary
    """
    init_vocab = list(map(lambda review: review, clean_documents_list["stemmed_reviews"]))
    model.build_vocab(init_vocab)
    return model

In [54]:
# 3. Training the model on the reviews, then saving it
def train_word2vec_model(model, clean_documents_list):
    """
    Input  : model and clean documents list
    Purpose: train model on clean documents list
    Output : trained model
    """
    corpus = list(map(lambda review: review, clean_documents_list["stemmed_reviews"]))
    model.train(corpus, total_examples=model.corpus_count, epochs=model.iter)
    model.save("word2vec.model")
    return model

In [55]:
# 4. Loading pre-trained model
def load_trained_model(model_name):
    """
    Input  : trained model name
    Purpose: load trained model
    Output : saved model
    """
    return gensim.models.Word2Vec.load("word2vec.model")

In [56]:
# 5. Getting embedded matrix from corpus
def get_word2vec_matrix(model):
    embedding_matrix = dict()
    for word in model.wv.vocab.keys():
        embedding_matrix[word] = list(model.wv[word])
    return pd.DataFrame(embedding_matrix)

In [58]:
# Instantiating and training model
model = create_word2vec_model()
model = init_vocab(model, reduced_df)
model = train_word2vec_model(model, reduced_df)
model = load_trained_model("word2vec.model")

# Testing for an example
model.most_similar("great", topn=10)

C:\Users\LEON\Anaconda3\lib\site-packages\ipykernel_launcher.py:9: DeprecationWarning: Call to deprecated `iter` (Attribute will be removed in 4.0.0, use self.epochs instead).
  if __name__ == '__main__':
C:\Users\LEON\Anaconda3\lib\site-packages\ipykernel_launcher.py:8: DeprecationWarning: Call to deprecated `most_similar` (Method will be removed in 4.0.0, use self.wv.most_similar() instead).
  


[('superb', 0.792310357093811),
 ('excel', 0.7652319669723511),
 ('brilliant', 0.7343354225158691),
 ('outstand', 0.7075722217559814),
 ('love', 0.6906702518463135),
 ('spot', 0.6830048561096191),
 ('faultless', 0.6820341348648071),
 ('fantast', 0.6801029443740845),
 ('fun', 0.67723548412323),
 ('relax', 0.6718858480453491)]

In [59]:
# Retrieving embedding matrix
corpus_word2vecMatrix = get_word2vec_matrix(model)
print(corpus_word2vecMatrix.shape)
corpus_word2vecMatrix.head()

(300, 1278)


decid     visit       way      back   england       saw  establish  \
0  0.412417  0.476795 -0.106598  0.162331  0.107145 -0.215314  -0.017548   
1 -0.003393 -0.165455 -0.138401  0.054900  0.028504 -0.067063   0.056478   
2  0.226729 -0.494166 -0.219555  0.262298 -0.088872 -0.110763  -0.103431   
3  0.238297  0.416677 -0.029450  0.095993  0.155644  0.179707   0.077634   
4 -0.068234  0.122572  0.043795  0.266209  0.114518  0.122392   0.242520   

    english      beer   thought  ...   appetit    broken      pipe        45  \
0  0.241625  0.038465 -0.130219  ... -0.250671 -0.366363 -0.224248 -0.296203   
1 -0.075753 -0.124977 -0.082378  ... -0.007569  0.004242  0.053698  0.041371   
2 -0.245499  0.192870 -0.001141  ... -0.144690 -0.058607 -0.250377 -0.062961   
3  0.178074 -0.086265 -0.028404  ... -0.029356 -0.002065  0.119931  0.029547   
4  0.123978 -0.222509  0.049515  ...  0.067074 -0.010640  0.017679  0.041814   

      court     dairi    sorbet    mother    effort      aunt  
0 -0.204752 -0.293993 -0.292644 -0.147118 -0.092475 -0.296086  
1 -0.014640 -0.062441  0.058857 -0.025711 -0.029227  0.013302  
2 -0.142785 -0.006058 -0.105786 -0.173935 -0.229302 -0.047576  
3  0.127596 -0.098690 -0.030303  0.155667  0.108431 -0.002139  
4 -0.003292  0.030447 -0.026125 -0.063303  0.085140  0.032656  

[5 rows x 1278 columns]

## 3. FastText

## 4. Comparison of the performance of a Random Forest on different types of embedding

In [23]:
# First we split train/test data

df_dataset = reduced_df
n = len(df_dataset)
df_dataset.sample(n=n, random_state=16)
n = int(2 * n / 3)
df_dataset_train = df_dataset[:n]
df_dataset_test = df_dataset[n:]
print("Split train/test: ", df_dataset_train.shape, "VS", df_dataset_test.shape)
corpus_TFmatrix_train = get_TF_matrix(df_dataset_train.stemmed_reviews)
corpus_TFmatrix_test = get_TF_matrix(df_dataset_test.stemmed_reviews)
y_train=df_dataset_train.rating
y_test=df_dataset_test.rating

Split train/test:  (66, 2) VS (34, 2)


### Cosine distance classification

In [24]:
# Here we use the classifier defined in the handout on our dataset

def distance_classifier_cosine_traning(lsi_vector_trainDB):
    """
    Input  : LSI vectors
    Purpose: calculate cosine similarity matrix
    Output : return similarity matrix
    """
    #calculate cosine similarity matrix for all training document LSI vectors
    return similarities.MatrixSimilarity(lsi_vector_trainDB)

def distance_classifier_cosine_test(classification_model, training_data, test_doc_lsi_vector, N=1):
    """
    Input  : trained classifier model, the training data (list of descriptions), lsi vectors of a document and N nearest document in the training data base
    Purpose: calculate cosine similarity matrix against all training samples
    Output : return nearest N document and classes
    """
    cosine_similarities = classification_model[test_doc_lsi_vector]

    most_similar_document_test = training_data[np.argmax(cosine_similarities)]

    #calculate cosine similarity matrix for all training document LSI vectors
    return most_similar_document_test

def reco_rate(ref_labels, predicted_labels):
    commun_labels = (pd.np.array(ref_labels)==pd.np.array(predicted_labels)).sum()
    return 100 * commun_labels / len(ref_labels)

classification_model = distance_classifier_cosine_traning(lsi_model[corpus_TFmatrix_train])
classification_model

In [25]:
# We test on train data
dictionary = get_dictionary(df_dataset.stemmed_reviews)
predicted_ratings = [distance_classifier_cosine_test(classification_model, 
                                df_dataset_train.rating, 
                                get_lsi_vector(lsi_model, df_dataset_train.stemmed_reviews.iloc[i]))
                                for i in range(df_dataset_train.shape[0])]

print("Classifier performances on train DB: %.2f" % reco_rate(df_dataset_train.rating, predicted_ratings), "%")

Classifier performances on train DB: 100.00 %


Unsurprinsingly, the cosine distance classifier performs perfectly on test data because it by definition the distance of each stemmed review to itself is zero and the decision is easily made. Let's see how it performs on test data.

In [26]:
# We test on test Data
predicted_ratings_test = [distance_classifier_cosine_test(classification_model, 
                                 df_dataset_train.rating, 
                                 get_lsi_vector(lsi_model, 
                                               df_dataset_test.stemmed_reviews.iloc[i]
                                              ))
                   for i in range(df_dataset_test.shape[0])]

print("Classifier performances on test DB: %.2f"%(reco_rate(df_dataset_test.rating, predicted_ratings_test)), "%")


Classifier performances on test DB: 41.18 %


In [27]:
# We take a look at the test reviews and their ratings 
df_dataset_test[:10]

stemmed_reviews  rating
66  [select, lunch, south, african, busi, guest, c...       4
67  [miss, love, indonesian, cuisin, holiday, hop,...       4
68  [great, good, wine, list, attent, courteou, se...       5
69  [friend, went, weekend, absolut, love, believ,...       4
70  [first, time, visit, sceneri, took, breath, aw...       4
71  [love, pint, beer, littl, els, call, windsor, ...       3
72  [spanish, tapa, best, great, locat, realli, go...       5
73  [time, lunch, work, peopl, last, time, worst, ...       3
74  [stay, close, good, littl, place, good, locat,...       4
75  [got, introduc, friend, hook, triangl, love, h...       5

In [28]:
# Here is our prediction
predicted_ratings_test[:10]

[5, 5, 5, 3, 5, 3, 5, 2, 5, 5]

As we see, the cosine classifier performs very poorly on test data using LSI embedding, we switch to random forest classification

### Random Forest Classification

In [38]:
def model_training(clf,X_train,y_train):
    """
    Input  : LSI vectors
    Purpose: train classification model
    Output : return trained classifier
    """
    clf.fit(X_train,y_train)
    return clf

def model_predictions(clf, X_test):
    """
    Input  : trained classifier model, the test set
    Purpose: make predictions on test data
    Output : predictions
    """
    y_pred=clf.predict(X_test)
    
    return y_pred

def reco_rate(ref_labels, predicted_labels):
    commun_labels = (pd.np.array(ref_labels)==pd.np.array(predicted_labels)).sum()
    return 100 * commun_labels / len(ref_labels)

In [39]:
from sklearn.ensemble import RandomForestClassifier
clf=RandomForestClassifier()

#### LSI

In [40]:
clf=model_training(clf,np.array(lsi_model[corpus_TFmatrix_train])[:,:,1],y_train)

# We test on train data
predicted_ratings = model_predictions(clf, np.array(lsi_model[corpus_TFmatrix_train])[:,:,1])
print("Classifier performances on train DB: %.2f" % reco_rate(df_dataset_train.rating, predicted_ratings), "%")

# We test on test Data
predicted_ratings_test = model_predictions(clf, np.array(lsi_model[corpus_TFmatrix_test])[:,:,1])
print("Classifier performances on test DB: %.2f"%(reco_rate(df_dataset_test.rating, predicted_ratings_test)), "%")

Classifier performances on train DB: 98.48 %
Classifier performances on test DB: 44.12 %


C:\Users\LEON\Anaconda3\lib\site-packages\sklearn\ensemble\forest.py:245: FutureWarning: The default value of n_estimators will change from 10 in version 0.20 to 100 in 0.22.
  "10 in version 0.20 to 100 in 0.22.", FutureWarning)


#### Word2Vec

In [64]:
def document_vector(model, doc):
    ##remove words that aren't in vocabulary
    doc = [word for word in doc if word in model.wv.vocab.keys()]
    return np.sum(model[doc], axis=0)

In [65]:
x = []
for doc in df_dataset_train.stemmed_reviews: # append the vector for each document
    x.append(document_vector(model, doc))
X_train = np.array(x)

x = []
for doc in df_dataset_test.stemmed_reviews: # append the vector for each document
    x.append(document_vector(model, doc))
X_test = np.array(x)

C:\Users\LEON\Anaconda3\lib\site-packages\ipykernel_launcher.py:4: DeprecationWarning: Call to deprecated `__getitem__` (Method will be removed in 4.0.0, use self.wv.__getitem__() instead).
  after removing the cwd from sys.path.


In [66]:
clf=RandomForestClassifier()
clf=model_training(clf,X_train,y_train)

# We test on train data
predicted_ratings = model_predictions(clf, X_train)
print("Classifier performances on train DB: %.2f" % reco_rate(df_dataset_train.rating, predicted_ratings), "%")

# We test on test Data
predicted_ratings_test = model_predictions(clf, X_test)
print("Classifier performances on test DB: %.2f"%(reco_rate(df_dataset_test.rating, predicted_ratings_test)), "%")

Classifier performances on train DB: 96.97 %
Classifier performances on test DB: 38.24 %


C:\Users\LEON\Anaconda3\lib\site-packages\sklearn\ensemble\forest.py:245: FutureWarning: The default value of n_estimators will change from 10 in version 0.20 to 100 in 0.22.
  "10 in version 0.20 to 100 in 0.22.", FutureWarning)
